// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dash.Models
{
    public partial class Carros
    {
        public Carros()
        {
            Vendas = new HashSet<Vendas>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Modelo { get; set; }
        public short Ano { get; set; }
        [Required]
        [StringLength(15)]
        [Unicode(false)]
        public string Cor { get; set; }
        [Column(TypeName = "money")]
        public decimal Preco { get; set; }
        public int QuantidadeEstoque { get; set; }

        [InverseProperty("IdCarroNavigation")]
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}