// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dash.Models
{
    [Index(nameof(Email), Name = "UQ__Clientes__A9D10534E0A7DE47", IsUnique = true)]
    [Index(nameof(Documento), Name = "UQ__Clientes__AF73706DD2FFAB3E", IsUnique = true)]
    public partial class Clientes
    {
        public Clientes()
        {
            Vendas = new HashSet<Vendas>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        public int Documento { get; set; }
        [Required]
        [StringLength(15)]
        [Unicode(false)]
        public string Genero { get; set; }
        public int Idade { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataCadastro { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Email { get; set; }
        public int Telefone { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string Estado { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}