// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dash.Models
{
    public partial class Vendas
    {
        [Key]
        public int IdVenda { get; set; }
        public int? IdCarro { get; set; }
        public int? IdCliente { get; set; }
        public int? IdVendedor { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataVenda { get; set; }
        [Required]
        [StringLength(15)]
        [Unicode(false)]
        public string FormaPagamento { get; set; }
        [Required]
        [StringLength(15)]
        [Unicode(false)]
        public string StatusVenda { get; set; }
        [Column(TypeName = "money")]
        public decimal ValorVenda { get; set; }

        [ForeignKey(nameof(IdCarro))]
        [InverseProperty(nameof(Carros.Vendas))]
        public virtual Carros IdCarroNavigation { get; set; }
        [ForeignKey(nameof(IdCliente))]
        [InverseProperty(nameof(Clientes.Vendas))]
        public virtual Clientes IdClienteNavigation { get; set; }
        [ForeignKey(nameof(IdVendedor))]
        [InverseProperty(nameof(Vendedores.Vendas))]
        public virtual Vendedores IdVendedorNavigation { get; set; }
    }
}