// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dash.Models
{
    public partial class Vendedores
    {
        public Vendedores()
        {
            Vendas = new HashSet<Vendas>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Area { get; set; }

        [InverseProperty("IdVendedorNavigation")]
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}